### ISSUE TITLE
Internal HW2 install N64

### ISSUE THREAD

**Issue by browntownington** [GrechTech/Rosetta#1]
Hello, 

Your Rosetta project is super neat - especially for external install!

I'm looking to do an internal install HW2 with active port detection for N64.

Your documentation on tindie and github contains a lot of details. But I am still a little bit stumped on what the advantages would be for me to use the Rosetta board and or N64 pinout board.

Mostly I don't understand this "significantly reducing the amount of external wiring required by using the unique open source RetroRosetta IO header that pairs all of BlueRetro's configuration IO pins with the GND or 3.3V pin needed to set them." I assume this is to help with the external installs rather than internal?

If I don't use RetroRosetta . I have wire for each controller data line and port trigger, gnd, 3v. 10 in total to the ESP.
https://github.com/nostalgic-indulgences/BlueRetro_Internal_Installation/blob/main/Nintendo%2064/Stage%20II%20-%20Port%20Detection%20(Current%20Trigger)/BlueRetro%20-%20N64%20(Stage%20II%20-%20Current%20Trigger)%20Internal%20Installation%20Diagram.png

**Comment by GrechTech** [comment]
Hi

Thanks!



That point about wiring primarily relates to older consoles, and universal units/firmware, as older consoles require upto 100 additional connections between eve shifters, and universal firmware 10-20 additional wires to ground or 3V3 (besides the controller ones) to set the configuration IO values, eg from the BlueRetro Cable Build Instructions for N64, 11 extra wires are usually required to set the config pins:





With RetroRosetta, none of these cables are required as each of the configuration IO pins are put on a double row GPIO header, where the paired pin of each row corresponds to GND or 3V3, so that these configuration pins can instead be set with 2.54mm jumper blocks, instead of wires.



With RetroRosetta V2 and the per console pinout boards, these config pins are connected internally on the consoles pinout PCB, and additionally the many other connections required for older (5V) consoles to interface with level shifter ICs.



I think for N64 HW2 internal install and other 3.3V systems (PS1 or newer), there's relatively less benefit to RetroRosetta's approach, with a roughly similar amount of wiring as full DIY, though you do get mounting screw holes, a fixed LED, and compared to using a standalone ESP32-WROOM-32 module, you get a full power stage that provides a more stable power input



Thanks

Thomas
GrechTech








---- On Thu, 12 Oct 2023 03:16:54 +0100 browntownington ***@***.***> wrote ---





Hello,

Your Rosetta project is super neat - especially for external install!

I'm looking to do an internal install HW2 will active port detection for N64.

Your documentation on tindie and github contains a lot of details. But I am still a little bit stumped on what the advantages would be for me to use the Rosetta board and or N64 pinout board.

Mostly I don't understand this "significantly reducing the amount of external wiring required by using the unique open source RetroRosetta IO header that pairs all of BlueRetro's configuration IO pins with the GND or 3.3V pin needed to set them."

If I don't use RetroRosetta . I have wire for each controller data line and port trigger, gnd, 3v. 10 in total to the ESP.
 https://github.com/nostalgic-indulgences/BlueRetro_Internal_Installation/blob/main/Nintendo%2064/Stage%20II%20-%20Port%20Detection%20(Current%20Trigger)/BlueRetro%20-%20N64%20(Stage%20II%20-%20Current%20Trigger)%20Internal%20Installation%20Diagram.png
